title: "UVic Programming Club"
author: "UVic Programming Club"
description: "<p style=\"color: #ffd700;\">Register to become a club member</p>"
descriptionlink: "https://docs.google.com/forms/d/e/1FAIpQLScf1nH3PjXlZTyN2Cytj8U0AUvHnxP6dWyfjxWhwMxJAN0mnQ/viewform?usp=sf_link"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
mathjax: true              # math notation
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "activities.html"}
  - {file: "contact.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/uvicprogrammingclub/uvicprogrammingclub.github.io"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
  - jekyll-feed
